### PR TITLE
Possible typo fix - Pretty confident this will resolve all problems. 

### PR DESCRIPTION
**Pull request by sryu1**

### CODE REVIEW

**Comment by sryu1** [comment]
@ZorkaA What exactly is the typo causing?

**Comment by ZorkaA** [comment]
Untitled

**Comment by sryu1** [comment]
Is that what the typo is causing or what my pull request causing?

**Comment by sryu1** [comment]
Seems like defaults.xml doesn't exist in any of the Dromader repos...

**Comment by ZorkaA** [comment]
Exactly, which is why it makes it even more confusing. Thanks though, at least it loads correctly now :)

**Pull request merged**
